### ISSUE TITLE
Almost read in data

### ISSUE THREAD

**Issue by Kbeggen42** [Kbeggen42/wolf-depredation#2]
Hey @AaronGullickson -- I'm so painfully close to reading in my data. It's in csv file format in my raw data folder. My only issue is RStudio seems very upset about my working directory-- I'm very sure I have it set in the right place (but I guess not)

**Comment by AaronGullickson** [comment]
Yes, this was a [discovery about quarto](https://quarto.org/docs/projects/code-execution.html#working-dir). It always wants to run from the directory of the file not the working directory unless we set that as an execution parameter. I am going to fix this in the template, but the easiest solution to this problem is just to use the `here` package, which is best practice anyway:

```r
cattle_pop <- read_fwf(here("data","data_raw","cattle_numbers.csv"))
cattle_loss <- read_fwf(here("data","data_raw","cattle_loss.csv"))
wolf_data <- read_fwf(here("data","data_raw","wolf_data.csv"))
```
